version: '2'
services:
  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: datapipeline

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  db-data: